import type { Subject, SubjectType } from './index';

/**
 * Complete AP Subject configurations
 * Only AP CSA has working functionality, but UI accommodates all
 */
export const AP_SUBJECTS: Record<SubjectType, Subject> = {
  // ============================================
  // COMPUTER SCIENCE (Active)
  // ============================================
  'ap-csa': {
    id: 'ap-csa',
    name: 'AP Computer Science A',
    shortName: 'CS A',
    icon: '💻',
    color: '#E07856',
    description: 'Object-oriented programming in Java, including classes, objects, inheritance, and algorithms.',
    examFormat: {
      mcqCount: 40,
      mcqTimeMinutes: 90,
      mcqPercentage: 50,
      frqCount: 4,
      frqTimeMinutes: 90,
      frqPercentage: 50,
      totalTimeMinutes: 180,
    },
    isActive: true,
  },

  // ============================================
  // MATHEMATICS
  // ============================================
  'ap-calc-ab': {
    id: 'ap-calc-ab',
    name: 'AP Calculus AB',
    shortName: 'Calc AB',
    icon: '📐',
    color: '#6B9E78',
    description: 'Limits, derivatives, integrals, and the Fundamental Theorem of Calculus.',
    examFormat: {
      mcqCount: 45,
      mcqTimeMinutes: 105,
      mcqPercentage: 50,
      frqCount: 6,
      frqTimeMinutes: 90,
      frqPercentage: 50,
      totalTimeMinutes: 195,
    },
    isActive: false,
  },
  'ap-calc-bc': {
    id: 'ap-calc-bc',
    name: 'AP Calculus BC',
    shortName: 'Calc BC',
    icon: '📊',
    color: '#5B8A72',
    description: 'All Calc AB topics plus sequences, series, parametric equations, and polar coordinates.',
    examFormat: {
      mcqCount: 45,
      mcqTimeMinutes: 105,
      mcqPercentage: 50,
      frqCount: 6,
      frqTimeMinutes: 90,
      frqPercentage: 50,
      totalTimeMinutes: 195,
    },
    isActive: false,
  },
  'ap-stats': {
    id: 'ap-stats',
    name: 'AP Statistics',
    shortName: 'Stats',
    icon: '📈',
    color: '#7B68EE',
    description: 'Exploring data, sampling, probability, and statistical inference.',
    examFormat: {
      mcqCount: 40,
      mcqTimeMinutes: 90,
      mcqPercentage: 50,
      frqCount: 6,
      frqTimeMinutes: 90,
      frqPercentage: 50,
      totalTimeMinutes: 180,
    },
    isActive: false,
  },

  // ============================================
  // SCIENCES
  // ============================================
  'ap-bio': {
    id: 'ap-bio',
    name: 'AP Biology',
    shortName: 'Biology',
    icon: '🧬',
    color: '#4CAF50',
    description: 'Evolution, cellular processes, genetics, and ecology.',
    examFormat: {
      mcqCount: 60,
      mcqTimeMinutes: 90,
      mcqPercentage: 50,
      frqCount: 6,
      frqTimeMinutes: 90,
      frqPercentage: 50,
      totalTimeMinutes: 180,
    },
    isActive: false,
  },
  'ap-chem': {
    id: 'ap-chem',
    name: 'AP Chemistry',
    shortName: 'Chemistry',
    icon: '⚗️',
    color: '#FF9800',
    description: 'Atomic structure, chemical bonding, reactions, and thermodynamics.',
    examFormat: {
      mcqCount: 60,
      mcqTimeMinutes: 90,
      mcqPercentage: 50,
      frqCount: 7,
      frqTimeMinutes: 105,
      frqPercentage: 50,
      totalTimeMinutes: 195,
    },
    isActive: false,
  },
  'ap-physics-1': {
    id: 'ap-physics-1',
    name: 'AP Physics 1',
    shortName: 'Physics 1',
    icon: '🎯',
    color: '#2196F3',
    description: 'Newtonian mechanics, work, energy, and rotational motion.',
    examFormat: {
      mcqCount: 50,
      mcqTimeMinutes: 90,
      mcqPercentage: 50,
      frqCount: 5,
      frqTimeMinutes: 90,
      frqPercentage: 50,
      totalTimeMinutes: 180,
    },
    isActive: false,
  },
  'ap-physics-2': {
    id: 'ap-physics-2',
    name: 'AP Physics 2',
    shortName: 'Physics 2',
    icon: '⚡',
    color: '#03A9F4',
    description: 'Thermodynamics, fluid mechanics, electricity, magnetism, and optics.',
    examFormat: {
      mcqCount: 50,
      mcqTimeMinutes: 90,
      mcqPercentage: 50,
      frqCount: 5,
      frqTimeMinutes: 90,
      frqPercentage: 50,
      totalTimeMinutes: 180,
    },
    isActive: false,
  },
  'ap-physics-c-mech': {
    id: 'ap-physics-c-mech',
    name: 'AP Physics C: Mechanics',
    shortName: 'Physics C Mech',
    icon: '⚙️',
    color: '#607D8B',
    description: 'Calculus-based mechanics including kinematics, dynamics, and oscillations.',
    examFormat: {
      mcqCount: 35,
      mcqTimeMinutes: 45,
      mcqPercentage: 50,
      frqCount: 3,
      frqTimeMinutes: 45,
      frqPercentage: 50,
      totalTimeMinutes: 90,
    },
    isActive: false,
  },
  'ap-physics-c-em': {
    id: 'ap-physics-c-em',
    name: 'AP Physics C: E&M',
    shortName: 'Physics C E&M',
    icon: '🔌',
    color: '#795548',
    description: 'Calculus-based electricity and magnetism.',
    examFormat: {
      mcqCount: 35,
      mcqTimeMinutes: 45,
      mcqPercentage: 50,
      frqCount: 3,
      frqTimeMinutes: 45,
      frqPercentage: 50,
      totalTimeMinutes: 90,
    },
    isActive: false,
  },
  'ap-environmental': {
    id: 'ap-environmental',
    name: 'AP Environmental Science',
    shortName: 'APES',
    icon: '🌍',
    color: '#8BC34A',
    description: 'Earth systems, ecosystems, natural resources, and environmental policy.',
    examFormat: {
      mcqCount: 80,
      mcqTimeMinutes: 90,
      mcqPercentage: 60,
      frqCount: 3,
      frqTimeMinutes: 70,
      frqPercentage: 40,
      totalTimeMinutes: 160,
    },
    isActive: false,
  },

  // ============================================
  // HISTORY & SOCIAL SCIENCES
  // ============================================
  'apush': {
    id: 'apush',
    name: 'AP US History',
    shortName: 'APUSH',
    icon: '🇺🇸',
    color: '#D32F2F',
    description: 'American history from pre-Columbian times to the present.',
    examFormat: {
      mcqCount: 55,
      mcqTimeMinutes: 55,
      mcqPercentage: 40,
      frqCount: 4,
      frqTimeMinutes: 100,
      frqPercentage: 60,
      totalTimeMinutes: 195,
    },
    isActive: false,
  },
  'ap-world': {
    id: 'ap-world',
    name: 'AP World History: Modern',
    shortName: 'World',
    icon: '🌎',
    color: '#9C27B0',
    description: 'Global history from 1200 CE to the present.',
    examFormat: {
      mcqCount: 55,
      mcqTimeMinutes: 55,
      mcqPercentage: 40,
      frqCount: 4,
      frqTimeMinutes: 100,
      frqPercentage: 60,
      totalTimeMinutes: 195,
    },
    isActive: false,
  },
  'ap-euro': {
    id: 'ap-euro',
    name: 'AP European History',
    shortName: 'Euro',
    icon: '🏰',
    color: '#673AB7',
    description: 'European history from 1450 to the present.',
    examFormat: {
      mcqCount: 55,
      mcqTimeMinutes: 55,
      mcqPercentage: 40,
      frqCount: 4,
      frqTimeMinutes: 100,
      frqPercentage: 60,
      totalTimeMinutes: 195,
    },
    isActive: false,
  },
  'ap-gov': {
    id: 'ap-gov',
    name: 'AP US Government & Politics',
    shortName: 'Gov',
    icon: '🏛️',
    color: '#1565C0',
    description: 'Constitutional foundations, political institutions, and civic participation.',
    examFormat: {
      mcqCount: 55,
      mcqTimeMinutes: 80,
      mcqPercentage: 50,
      frqCount: 4,
      frqTimeMinutes: 100,
      frqPercentage: 50,
      totalTimeMinutes: 180,
    },
    isActive: false,
  },
  'ap-econ-micro': {
    id: 'ap-econ-micro',
    name: 'AP Microeconomics',
    shortName: 'Micro',
    icon: '📉',
    color: '#00897B',
    description: 'Supply and demand, consumer behavior, and market structures.',
    examFormat: {
      mcqCount: 60,
      mcqTimeMinutes: 70,
      mcqPercentage: 66,
      frqCount: 3,
      frqTimeMinutes: 60,
      frqPercentage: 34,
      totalTimeMinutes: 130,
    },
    isActive: false,
  },
  'ap-econ-macro': {
    id: 'ap-econ-macro',
    name: 'AP Macroeconomics',
    shortName: 'Macro',
    icon: '📈',
    color: '#00ACC1',
    description: 'National income, inflation, unemployment, and monetary policy.',
    examFormat: {
      mcqCount: 60,
      mcqTimeMinutes: 70,
      mcqPercentage: 66,
      frqCount: 3,
      frqTimeMinutes: 60,
      frqPercentage: 34,
      totalTimeMinutes: 130,
    },
    isActive: false,
  },
  'ap-psych': {
    id: 'ap-psych',
    name: 'AP Psychology',
    shortName: 'Psych',
    icon: '🧠',
    color: '#E91E63',
    description: 'Scientific study of behavior and mental processes.',
    examFormat: {
      mcqCount: 100,
      mcqTimeMinutes: 70,
      mcqPercentage: 66,
      frqCount: 2,
      frqTimeMinutes: 50,
      frqPercentage: 34,
      totalTimeMinutes: 120,
    },
    isActive: false,
  },

  // ============================================
  // ENGLISH
  // ============================================
  'ap-lang': {
    id: 'ap-lang',
    name: 'AP English Language',
    shortName: 'Lang',
    icon: '✍️',
    color: '#FF5722',
    description: 'Rhetorical analysis, argumentation, and synthesis.',
    examFormat: {
      mcqCount: 45,
      mcqTimeMinutes: 60,
      mcqPercentage: 45,
      frqCount: 3,
      frqTimeMinutes: 135,
      frqPercentage: 55,
      totalTimeMinutes: 195,
    },
    isActive: false,
  },
  'ap-lit': {
    id: 'ap-lit',
    name: 'AP English Literature',
    shortName: 'Lit',
    icon: '📚',
    color: '#8D6E63',
    description: 'Literary analysis of prose fiction, poetry, and drama.',
    examFormat: {
      mcqCount: 55,
      mcqTimeMinutes: 60,
      mcqPercentage: 45,
      frqCount: 3,
      frqTimeMinutes: 120,
      frqPercentage: 55,
      totalTimeMinutes: 180,
    },
    isActive: false,
  },

  // ============================================
  // WORLD LANGUAGES
  // ============================================
  'ap-spanish': {
    id: 'ap-spanish',
    name: 'AP Spanish Language',
    shortName: 'Spanish',
    icon: '🇪🇸',
    color: '#FFC107',
    description: 'Spanish language skills in interpersonal, interpretive, and presentational communication.',
    examFormat: {
      mcqCount: 65,
      mcqTimeMinutes: 95,
      mcqPercentage: 50,
      frqCount: 4,
      frqTimeMinutes: 88,
      frqPercentage: 50,
      totalTimeMinutes: 183,
    },
    isActive: false,
  },
  'ap-french': {
    id: 'ap-french',
    name: 'AP French Language',
    shortName: 'French',
    icon: '🇫🇷',
    color: '#3F51B5',
    description: 'French language skills in interpersonal, interpretive, and presentational communication.',
    examFormat: {
      mcqCount: 65,
      mcqTimeMinutes: 95,
      mcqPercentage: 50,
      frqCount: 4,
      frqTimeMinutes: 88,
      frqPercentage: 50,
      totalTimeMinutes: 183,
    },
    isActive: false,
  },
  'ap-german': {
    id: 'ap-german',
    name: 'AP German Language',
    shortName: 'German',
    icon: '🇩🇪',
    color: '#212121',
    description: 'German language skills in interpersonal, interpretive, and presentational communication.',
    examFormat: {
      mcqCount: 65,
      mcqTimeMinutes: 95,
      mcqPercentage: 50,
      frqCount: 4,
      frqTimeMinutes: 88,
      frqPercentage: 50,
      totalTimeMinutes: 183,
    },
    isActive: false,
  },
  'ap-chinese': {
    id: 'ap-chinese',
    name: 'AP Chinese Language',
    shortName: 'Chinese',
    icon: '🇨🇳',
    color: '#F44336',
    description: 'Chinese language skills in interpersonal, interpretive, and presentational communication.',
    examFormat: {
      mcqCount: 70,
      mcqTimeMinutes: 95,
      mcqPercentage: 50,
      frqCount: 4,
      frqTimeMinutes: 88,
      frqPercentage: 50,
      totalTimeMinutes: 183,
    },
    isActive: false,
  },
  'ap-japanese': {
    id: 'ap-japanese',
    name: 'AP Japanese Language',
    shortName: 'Japanese',
    icon: '🇯🇵',
    color: '#E53935',
    description: 'Japanese language skills in interpersonal, interpretive, and presentational communication.',
    examFormat: {
      mcqCount: 70,
      mcqTimeMinutes: 95,
      mcqPercentage: 50,
      frqCount: 4,
      frqTimeMinutes: 88,
      frqPercentage: 50,
      totalTimeMinutes: 183,
    },
    isActive: false,
  },
};

// Helper functions
export function getSubject(id: SubjectType): Subject {
  return AP_SUBJECTS[id];
}

export function getActiveSubjects(): Subject[] {
  return Object.values(AP_SUBJECTS).filter((s) => s.isActive);
}

export function getAllSubjects(): Subject[] {
  return Object.values(AP_SUBJECTS);
}

export function getSubjectsByCategory(category: 'stem' | 'humanities' | 'languages'): Subject[] {
  const categories: Record<string, SubjectType[]> = {
    stem: [
      'ap-csa',
      'ap-calc-ab',
      'ap-calc-bc',
      'ap-stats',
      'ap-bio',
      'ap-chem',
      'ap-physics-1',
      'ap-physics-2',
      'ap-physics-c-mech',
      'ap-physics-c-em',
      'ap-environmental',
    ],
    humanities: [
      'apush',
      'ap-world',
      'ap-euro',
      'ap-gov',
      'ap-econ-micro',
      'ap-econ-macro',
      'ap-psych',
      'ap-lang',
      'ap-lit',
    ],
    languages: ['ap-spanish', 'ap-french', 'ap-german', 'ap-chinese', 'ap-japanese'],
  };

  return categories[category].map((id) => AP_SUBJECTS[id]);
}
